# Get the directory of the current Snakefile
TEST_ROOT_msa__muscle = Path(workflow.snakefile).parent


rule test_msa__muscle__all:
    input:
        files = [TEST_ROOT_msa__muscle/'test_output/test.fasta'],
        tests = [TEST_ROOT_msa__muscle/"tests.py"]
    conda: 'env.yaml'
    log: 
        stdout = TEST_ROOT_msa__muscle/"test_output/pytest.stdout.log",
        stderr = TEST_ROOT_msa__muscle/"test_output/pytest.stderr.log"
    shell: "cd {TEST_ROOT_msa__muscle} && pytest {input.tests} > {log.stdout} 2> {log.stderr}"

rule test_msa__muscle:
    input:
        sequences = TEST_ROOT_msa__muscle/'sequences.fasta'
    output:
        temp(TEST_ROOT_msa__muscle/'test_output/test.fasta')
    log:
        temp(TEST_ROOT_msa__muscle/'test_output/test.log')
    threads: 2
    wrapper:
        f"file:{TEST_ROOT_msa__muscle.parent}"
