# Get the directory of the current Snakefile
TEST_ROOT_cigarmath__slice = Path(workflow.snakefile).parent

rule test_cigarmath__slice__all:
    input:
        files = [TEST_ROOT_cigarmath__slice/'test_output/test_output.fastq',
                TEST_ROOT_cigarmath__slice/'test_output/test_metrics.yaml'],
        tests = [TEST_ROOT_cigarmath__slice/"tests.py"]
    conda: 'env.yaml'
    log: 
        stdout = TEST_ROOT_cigarmath__slice/"test_output/pytest.stdout.log",
        stderr = TEST_ROOT_cigarmath__slice/"test_output/pytest.stderr.log"
    shell: "cd {TEST_ROOT_cigarmath__slice} && pytest {input.tests} > {log.stdout} 2> {log.stderr}"

rule test_cigarmath__slice:
    input:
        TEST_ROOT_cigarmath__slice / 'test_output/test.bam'
    output:
        fastq = TEST_ROOT_cigarmath__slice / 'test_output/test_output.fastq',
        metrics = TEST_ROOT_cigarmath__slice / 'test_output/test_metrics.yaml'
    params:
        region='HXB2:110-130',
        region_name='test_region',
        sample_name='test_sample',
        min_mapq=20,
        append_region_to_read_id=False
    wrapper:
        f"file:{TEST_ROOT_cigarmath__slice.parent}"

rule:
    input:
        TEST_ROOT_cigarmath__slice / 'test.sam'
    output:
        temp(TEST_ROOT_cigarmath__slice / 'test_output/test.bam')
    params:
        extra = '-n'
    wrapper:
        f"{WRAPPER_VERSION}/bio/samtools/sort" 