# Get the directory of the current Snakefile
TEST_ROOT_phylo__fasttree = Path(workflow.snakefile).parent

rule test_phylo__fasttree__all:
    input:
        files = [TEST_ROOT_phylo__fasttree/'test_output/test.newick'],
        tests = [TEST_ROOT_phylo__fasttree/"tests.py"]
    conda: 'env.yaml'
    log: 
        stdout = TEST_ROOT_phylo__fasttree/"test_output/pytest.stdout.log",
        stderr = TEST_ROOT_phylo__fasttree/"test_output/pytest.stderr.log"
    shell: "cd {TEST_ROOT_phylo__fasttree} && pytest {input.tests} > {log.stdout} 2> {log.stderr}"

rule test_phylo__fasttree:
    input:
        alignment = TEST_ROOT_phylo__fasttree/'alignment.fasta'
    output:
        temp(TEST_ROOT_phylo__fasttree/'test_output/test.newick')
    log:
        temp(TEST_ROOT_phylo__fasttree/'test_output/test.log')
    threads: 2
    wrapper:
        f"file:{TEST_ROOT_phylo__fasttree.parent}"
