# Get the directory of the current Snakefile
TEST_ROOT_phylo__reroot = Path(workflow.snakefile).parent


rule test_phylo__reroot__all:
    input:
        files = [TEST_ROOT_phylo__reroot/'test_output/test_rerooted.newick'],
        tests = [TEST_ROOT_phylo__reroot/"tests.py"]
    conda: 'env.yaml'
    log:
        stdout = TEST_ROOT_phylo__reroot/"test_output/pytest.stdout.log",
        stderr = TEST_ROOT_phylo__reroot/"test_output/pytest.stderr.log"
    shell: "cd {TEST_ROOT_phylo__reroot} && pytest {input.tests} > {log.stdout} 2> {log.stderr}"

rule test_phylo__reroot:
    input:
        tree = TEST_ROOT_phylo__reroot/'test.newick'
    output:
        temp(TEST_ROOT_phylo__reroot/'test_output/test_rerooted.newick')
    params:
        root_taxon = "Seq1"
    wrapper:
        f"file:{TEST_ROOT_phylo__reroot.parent}"
