# Get the directory of the current Snakefile
TEST_ROOT_cigarmath__pileup = Path(workflow.snakefile).parent


rule test_cigarmath__pileup__all:
    input:
        files = [TEST_ROOT_cigarmath__pileup/'test_output/test_output.tsv'],
        tests = [TEST_ROOT_cigarmath__pileup/"tests.py"]
    conda: 'env.yaml'
    log: 
        stdout = TEST_ROOT_cigarmath__pileup/"test_output/pytest.stdout.log",
        stderr = TEST_ROOT_cigarmath__pileup/"test_output/pytest.stderr.log"
    shell: "cd {TEST_ROOT_cigarmath__pileup} && pytest {input.tests} > {log.stdout} 2> {log.stderr}"

rule test_cigarmath__pileup:
    input:
        TEST_ROOT_cigarmath__pileup / 'test_output/test.bam'
    output:
        TEST_ROOT_cigarmath__pileup / 'test_output/test_output.tsv'
    params:
        min_mapq = 20
    wrapper:
        f"file:{TEST_ROOT_cigarmath__pileup.parent}"


rule:
    input:
        TEST_ROOT_cigarmath__pileup / '../../test_data/test.sam'
    output:
        temp(TEST_ROOT_cigarmath__pileup / 'test_output/test.bam')
    params:
        extra = '-n'
    wrapper:
        f"{WRAPPER_VERSION}/bio/samtools/sort" 
